### ISSUE TITLE
How can these be centered vertically?

### ISSUE THREAD

**Issue by dlamon1** [luluvia/svelte-svg-spinners#1]
It seems that these are falling on the text-baseline, so there is a slight margin on the bottom.

**Comment by luluvia** [comment]
Hi, thank you for reporting this. It looks like I'm not seeing the same when I vertically align using a containing div:

![image](https://user-images.githubusercontent.com/43284013/207774053-7268e9dd-1072-47e4-9a7b-4cc5d8b7858e.png)

Even when the div is the same height as the spinner, I'm not seeing any alignment issues: 
![image](https://user-images.githubusercontent.com/43284013/207774157-f24fe4b8-da2e-42cb-9b60-7406229c8c5a.png)

Can you provide an example of where the alignment/margin issues happen? Centering with a div seems to work just fine both vertically and horizontally on my end.

**Comment by dlamon1** [comment]
Sorry the only issue is with me! I had a parent element that was affecting the positioning.
